---
services:

  door_opener_async:
    image: door_opener_async:latest

    build: ./build

    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.enable=false"

    container_name: door_opener_async

    env_file:
      - environment

    restart: always
    network_mode: host
